# Generated by Django 3.1.7 on 2021-03-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210324_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='artist_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
